### ISSUE TITLE
What is the GMFSS_Fortuna Node?

### ISSUE THREAD

**Issue by PaulFidika** [kijai/ComfyUI-SVD#5]
Sorry if this is a dumb question, but what is that node and where do I get it? I found their main Github repo, but I can't find any ComfyUI nodes with that name

https://github.com/98mxr/GMFSS_Fortuna

**Comment by kijai** [comment]
It's a frame interpolation node from here, the pack has many options, like RIFE, FILM and Fortuna (and more):
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation

**Comment by PaulFidika** [comment]
Great! Thanks for putting this node together so quickly; amazing
