### ISSUE TITLE
Following node types were not found:

### ISSUE THREAD

**Issue by Nebuluss** [kijai/ComfyUI-SVD#6]
When loading the graph, the following node types were not found:
SVDModelLoader
SVDDecoder
Nodes that have failed to load will show as red on the graph.

** ComfyUI start up time: 2023-11-23 17:51:59.587594

Prestartup times for custom nodes:
   0.0 seconds: D:\COMFYVIDEOS\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65349 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1719 [d03d8aa2] | Released on '2023-11-23'

Import times for custom nodes:
   0.0 seconds: D:\COMFYVIDEOS\ComfyUI\custom_nodes\ComfyUI-SVD
   0.2 seconds: D:\COMFYVIDEOS\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\COMFYVIDEOS\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by PaulFidika** [comment]
Are you in the wrong repo? I think the nodes you're referring to are here, which is an alternative implementation of SVD:

https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion

**Comment by Nebuluss** [comment]
yep totatlly sorry had the two repo open
