### ISSUE TITLE
Standardized Model Location

### ISSUE THREAD

**Issue by opensourcefan** [kijai/ComfyUI-SVD#8]
Would it be possible to move the Model load directory to `ComfyUI/models/SVD` and `ComfyUI/models/SVD_configs` or something more accessible by anyone making nodes? These rather large models are not conducive to have multiples of.  

Or can we provide an override option on a node to input whatever directory path we're using?

Thank you

**Comment by kijai** [comment]
Yeah it would be, but comfy just added official implementation so this is redundant.

**Comment by opensourcefan** [comment]
^
