### ISSUE TITLE
Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SVD module for custom nodes: cannot import name 'NODE_CLASS_MAPPINGS' from 'ComfyUI-SVD.comfyui_svd' (F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SVD\comfyui_svd.py)

### ISSUE THREAD

**Issue by xueqing0622** [kijai/ComfyUI-SVD#9]
this extension effect is more better than comfyui office, but today show error:

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SVD module for custom nodes: cannot import name 'NODE_CLASS_MAPPINGS' from 'ComfyUI-SVD.comfyui_svd' (F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SVD\comfyui_svd.py)

**Comment by xueqing0622** [comment]
ok, I know why!

**Comment by xueqing0622** [comment]
by the way, how to set office parameter to get the same effect by your extension

**Comment by xsw302** [comment]
> ok, I know why!好吧，我知道为什么！

I have the same problem, how did you solve it?

**Comment by xsw302** [comment]
> ok, I know why!

I have the same problem, how did you solve it?

**Comment by xueqing0622** [comment]
> > ok, I know why!
> 
> I have the same problem, how did you solve it?

He finally commented out the script, so you can just go back to the version.

**Comment by OtakuFra** [comment]
i get the same issue
`Cannot import D:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-SVD module for custom nodes: cannot import name 'NODE_CLASS_MAPPINGS' from 'ComfyUI-SVD.comfyui_svd' (D:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-SVD\comfyui_svd.py)`

**Comment by xueqing0622** [comment]
The author doesn't even have to use it, so there's no need to agonize!!!!
